package app.imalibrarian.domain.model

data class Book(
    val id: Long = 0,
    val title: String = "",
    val subtitle: String = "",
    val isbn10: String = "",
    val isbn13: String = "",
    val publisher: String = "",
    val placeOfPublication: String = "",
    val pageCount: Int = 0,
    val language: String = "",
    val originalPublicationYear: Int? = null,
    val editionPublicationYear: Int? = null,
    val editionNumber: Int? = null,
    val printingNumber: Int? = null,
    val genre: String = "",
    val subgenre: String = "",
    val dateAcquired: Long? = null,
    val purchasePrice: String = "",
    val sourceOfPurchase: String = "",
    val shelfLocation: String = "",
    val readStatus: ReadStatus = ReadStatus.UNREAD,
    val rating: Int = 0,
    val personalNotes: String = "",
    val isFavourite: Boolean = false,
    val seriesName: String = "",
    val seriesNumber: Int? = null,
    val coverImagePath: String = "",
    val dateAdded: Long = System.currentTimeMillis()
)